// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uihnsmmcgiszhuzzqroi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaG5zbW1jZ2lzemh1enpxcm9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxODgxNzEsImV4cCI6MjA4NDc2NDE3MX0.jBllsTzihPf4rCPnJ3uR_gBv0p8NwR37T0qEYxPqUnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});